//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicesProxy.QuoteServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuoteServiceProxy.IQuoteService")]
    public interface IQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/GetQuotes", ReplyAction="http://tempuri.org/IQuoteService/GetQuotesResponse")]
        System.Collections.Generic.List<Model.Bar> GetQuotes(string symbol, System.DateTime from, System.DateTime to, Model.Interval interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/GetQuotes", ReplyAction="http://tempuri.org/IQuoteService/GetQuotesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Model.Bar>> GetQuotesAsync(string symbol, System.DateTime from, System.DateTime to, Model.Interval interval);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuoteServiceChannel : WcfServicesProxy.QuoteServiceProxy.IQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuoteServiceClient : System.ServiceModel.ClientBase<WcfServicesProxy.QuoteServiceProxy.IQuoteService>, WcfServicesProxy.QuoteServiceProxy.IQuoteService {
        
        public QuoteServiceClient() {
        }
        
        public QuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Model.Bar> GetQuotes(string symbol, System.DateTime from, System.DateTime to, Model.Interval interval) {
            return base.Channel.GetQuotes(symbol, from, to, interval);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Model.Bar>> GetQuotesAsync(string symbol, System.DateTime from, System.DateTime to, Model.Interval interval) {
            return base.Channel.GetQuotesAsync(symbol, from, to, interval);
        }
    }
}
