//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicesProxy.SymbolServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SymbolServiceProxy.ISymbolService")]
    public interface ISymbolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISymbolService/GetSymbols", ReplyAction="http://tempuri.org/ISymbolService/GetSymbolsResponse")]
        Model.Symbol[] GetSymbols();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISymbolService/GetSymbols", ReplyAction="http://tempuri.org/ISymbolService/GetSymbolsResponse")]
        System.Threading.Tasks.Task<Model.Symbol[]> GetSymbolsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISymbolService/Get", ReplyAction="http://tempuri.org/ISymbolService/GetResponse")]
        Model.Symbol Get(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISymbolService/Get", ReplyAction="http://tempuri.org/ISymbolService/GetResponse")]
        System.Threading.Tasks.Task<Model.Symbol> GetAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISymbolServiceChannel : WcfServicesProxy.SymbolServiceProxy.ISymbolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SymbolServiceClient : System.ServiceModel.ClientBase<WcfServicesProxy.SymbolServiceProxy.ISymbolService>, WcfServicesProxy.SymbolServiceProxy.ISymbolService {
        
        public SymbolServiceClient() {
        }
        
        public SymbolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SymbolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SymbolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SymbolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.Symbol[] GetSymbols() {
            return base.Channel.GetSymbols();
        }
        
        public System.Threading.Tasks.Task<Model.Symbol[]> GetSymbolsAsync() {
            return base.Channel.GetSymbolsAsync();
        }
        
        public Model.Symbol Get(string name) {
            return base.Channel.Get(name);
        }
        
        public System.Threading.Tasks.Task<Model.Symbol> GetAsync(string name) {
            return base.Channel.GetAsync(name);
        }
    }
}
